package com.enjoytrip.dto.attraction;

public enum AttractionSortOrder {
	DICTIONARY_ASC,
	DICTIONARY_DESC,
	READCOUNT_ASC,
	READCOUNT_DESC,
	BOOKMARK_ASC,
	BOOKMARK_DESC,
	LIKE_ASC,
	LIKE_DESC,
	RATING_ASC,
	RATING_DESC,
	COMMENT_ASC,
	COMMENT_DESC
}
