package com.enjoytrip.dto.attraction;

public enum AttractionSortOrder {
	DICTIONARY_ASC,
	DICTIONARY_DESC,
	READCOUNT_ASC,
	READCOUNT_DESC,
	BOOKMARK_ASC,
	BOOKMARK_DESC,
	FAVOR_ASC,
	FAVOR_DESC,
	RATING_ASC,
	RATING_DESC
}
