package com.enjoytrip.dto.plan;

public enum PlanSearchOrder {
	DICTIONARY_ASC,
	DICTIONARY_DESC,
	COMMENT_ASC,
	COMMENT_DESC,
	FAVOR_ASC,
	FAVOR_DESC,
	BOOKMARK_ASC,
	BOOKMARK_DESC,
	READCOUNT_ASC,
	READCOUNT_DESC
}
